-- 코드를 작성해주세요
SELECT SUM(SCORE) AS SCORE, EMP_NO, EMP_NAME, POSITION, EMAIL
  FROM HR_EMPLOYEES
  LEFT JOIN HR_DEPARTMENT USING(DEPT_ID)
  LEFT JOIN HR_GRADE USING(EMP_NO)
  GROUP BY EMP_NO
  ORDER BY SCORE DESC LIMIT 1;
