-- 코드를 작성해주세요
SELECT ITEM_INFO.ITEM_ID, ITEM_INFO.ITEM_NAME, ITEM_INFO.RARITY
  FROM ITEM_TREE
  RIGHT JOIN ITEM_INFO
    ON ITEM_TREE.PARENT_ITEM_ID = ITEM_INFO.ITEM_ID
  WHERE ITEM_TREE.ITEM_ID IS NULL
  ORDER BY ITEM_INFO.ITEM_ID DESC;