-- 코드를 작성해주세요
SELECT ID, FISH_NAME, LENGTH
 FROM FISH_INFO LEFT JOIN FISH_NAME_INFO USING(FISH_TYPE)
WHERE (FISH_TYPE, LENGTH) IN
        (SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
          FROM FISH_INFO
         WHERE LENGTH IS NOT NULL
         GROUP BY FISH_TYPE)
ORDER BY ID ASC;